version: '{build}'
image: Visual Studio 2017
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
clone_depth: 1
test_script:
  - cmd: dotnet restore
  - cmd: dotnet test
deploy: off
